#!/usr/bin/env bash

export $(cat .env | xargs)

# if [[ -z $QUEUE_RUNNER_HOSTNAME ]] || [[ $QUEUE_RUNNER_HOSTNAME == $(hostname) ]] ; then
# 	export PROCFILE=Procfile
# else
# 	export PROCFILE=ProcfileRailsOnly
# fi

# echo $PROCFILE
forego start -f Procfile.dev
