default: &default
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379/1' } %>

development:
  <<: *default
  channel_prefix: default_app_name_development

test:
  <<: *default
  channel_prefix: default_app_name_test

production:
  <<: *default
  channel_prefix: default_app_name_production
