[
  { abbr: 'AK', full: 'Alaska',               ok_invite: true,  conference: 'Pacific',  is_foreign: false },
  { abbr: 'AL', full: 'Alabama',              ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'AR', full: 'Arkansas',             ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'AZ', full: 'Arizona',              ok_invite: true,  conference: 'Pacific',  is_foreign: false },
  { abbr: 'CA', full: 'California',           ok_invite: true,  conference: 'Pacific',  is_foreign: false },
  { abbr: 'CO', full: 'Colorado',             ok_invite: true,  conference: 'Mountain', is_foreign: false },
  { abbr: 'CT', full: 'Connecticut',          ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'DC', full: 'District of Columbia', ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'DE', full: 'Delaware',             ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'FL', full: 'Florida',              ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'GA', full: 'Georgia',              ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'HI', full: 'Hawaii',               ok_invite: false, conference: 'Pacific',  is_foreign: false },
  { abbr: 'IA', full: 'Iowa',                 ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'ID', full: 'Idaho',                ok_invite: true,  conference: 'Mountain', is_foreign: false },
  { abbr: 'IL', full: 'Illinois',             ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'IN', full: 'Indiana',              ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'KS', full: 'Kansas',               ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'KY', full: 'Kentucky',             ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'LA', full: 'Louisiana',            ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'MA', full: 'Massachusetts',        ok_invite: false, conference: 'East',     is_foreign: false },
  { abbr: 'MD', full: 'Maryland',             ok_invite: false, conference: 'East',     is_foreign: false },
  { abbr: 'ME', full: 'Maine',                ok_invite: false, conference: 'East',     is_foreign: false },
  { abbr: 'MI', full: 'Michigan',             ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'MN', full: 'Minnesota',            ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'MO', full: 'Missouri',             ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'MS', full: 'Mississippi',          ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'MT', full: 'Montana',              ok_invite: true,  conference: 'Mountain', is_foreign: false },
  { abbr: 'NC', full: 'North Carolina',       ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'ND', full: 'North Dakota',         ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'NE', full: 'Nebraska',             ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'NH', full: 'New Hampshire',        ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'NJ', full: 'New Jersey',           ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'NM', full: 'New Mexico',           ok_invite: true,  conference: 'Mountain', is_foreign: false },
  { abbr: 'NV', full: 'Nevada',               ok_invite: true,  conference: 'Pacific',  is_foreign: false },
  { abbr: 'NY', full: 'New York',             ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'OH', full: 'Ohio',                 ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'OK', full: 'Oklahoma',             ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'OR', full: 'Oregon',               ok_invite: true,  conference: 'Pacific',  is_foreign: false },
  { abbr: 'PA', full: 'Pennsylvania',         ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'RI', full: 'Rhode Island',         ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'SC', full: 'South Carolina',       ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'SD', full: 'South Dakota',         ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'TN', full: 'Tennessee',            ok_invite: false, conference: 'Central',  is_foreign: false },
  { abbr: 'TX', full: 'Texas',                ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'UT', full: 'Utah',                 ok_invite: true,  conference: 'Mountain', is_foreign: false },
  { abbr: 'VA', full: 'Virginia',             ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'VT', full: 'Vermont',              ok_invite: false, conference: 'East',     is_foreign: false },
  { abbr: 'WA', full: 'Washington',           ok_invite: true,  conference: 'Pacific',  is_foreign: false },
  { abbr: 'WI', full: 'Wisconsin',            ok_invite: true,  conference: 'Central',  is_foreign: false },
  { abbr: 'WV', full: 'West Virginia',        ok_invite: true,  conference: 'East',     is_foreign: false },
  { abbr: 'WY', full: 'Wyoming',              ok_invite: true,  conference: 'Mountain', is_foreign: false },
].each {|state| State.create(state) unless State.find_by(abbr: state[:abbr]) }
